version: "3.9"

services:
  sql-fcg-users:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql-fcg-users
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "NovaSenhaForte123!"
      MSSQL_PID: "Developer"
    ports:
      - "14331:1433"
    volumes:
      - sql_fcg_users_data:/var/opt/mssql

  sql-tools-fcg-users:
    image: mcr.microsoft.com/mssql-tools
    container_name: sql-tools-fcg-users
    depends_on:
      - sql-fcg-users
    entrypoint: /bin/bash
    command: >
      -c "
      echo 'Aguardando SQL Server...';
      until /opt/mssql-tools/bin/sqlcmd -S sql-fcg-users -U sa -P 'NovaSenhaForte123!' -Q 'SELECT 1' &> /dev/null; do
        sleep 2;
      done;
      echo 'SQL Server pronto. Criando banco se n√£o existir...';
      /opt/mssql-tools/bin/sqlcmd -S sql-fcg-users -U sa -P 'NovaSenhaForte123!' -Q \"IF DB_ID('fcg-users') IS NULL CREATE DATABASE [fcg-users]\"
      "

  elastic-fcg-user:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: elastic-fcg-user
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - elastic_fcg_user_data:/usr/share/elasticsearch/data

volumes:
  sql_fcg_users_data:
  elastic_fcg_user_data: