version: "3.9"

services:
  sql-fcg-user:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql-fcg-user
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "NovaSenhaForte123!"
      MSSQL_PID: "Developer"
    ports:
      - "14331:1433"
    volumes:
      - sql_fcg_user_data:/var/opt/mssql
    command: >
      /bin/bash -c "
      /opt/mssql/bin/sqlservr &
      sleep 20 &&
      /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P 'NovaSenhaForte123!' -Q 'CREATE DATABASE [fcg-user]' &&
      wait
      "

  elastic-fcg-user:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: elastic-fcg-user
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - elastic_fcg_user_data:/usr/share/elasticsearch/data

volumes:
  sql_fcg_user_data:
  elastic_fcg_user_data: